# Site settings
title: Tutorial Penggunaan Inspekta
email: isolinktechnology@gmail.com
description: Tutorial Site
baseurl: /tutorial/
url: https://isolinktechnology.github.io/
twitter_username:
github_username:  

# Build settings
markdown: kramdown
permalink: pretty

# Theme
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
